# Generated by Django 3.0.6 on 2020-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='button',
            field=models.CharField(blank=True, default='Подробнее ...', max_length=50, null=True, verbose_name='Название перехода'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка перехода'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название слайда'),
        ),
    ]
