# Generated by Django 3.0.6 on 2020-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200712_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='Main', max_length=50, verbose_name='Название слайда'),
            preserve_default=False,
        ),
    ]
