# Generated by Django 3.0.6 on 2020-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200712_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='text_muted',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Второй текст'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.ImageField(upload_to='marketing/', verbose_name='Изображение'),
        ),
    ]
