# Generated by Django 3.0.6 on 2020-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200712_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='text_muted',
            field=models.CharField(default='Супер!', max_length=100, verbose_name='Второй текст'),
            preserve_default=False,
        ),
    ]
