# Generated by Django 3.0.6 on 2020-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200712_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
