# Generated by Django 3.0.6 on 2020-07-24 12:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200724_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
