# Generated by Django 3.0.6 on 2020-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название издательства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О издательстве')),
            ],
        ),
    ]
