# Generated by Django 3.0.6 on 2020-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='Фантастика это такое!'),
            preserve_default=False,
        ),
    ]
