# Generated by Django 3.0.6 on 2020-07-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isdn',
        ),
    ]
