# Generated by Django 3.0.6 on 2020-07-05 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200705_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ent_date',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения в каталог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isdn',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
