# Generated by Django 3.0.6 on 2020-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_translater'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='Фото обложки'),
        ),
    ]
