# Generated by Django 3.0.6 on 2020-07-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200705_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isdn',
            new_name='isbn',
        ),
    ]
