# Generated by Django 3.0.6 on 2020-07-08 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('book', '0006_auto_20200707_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='genre.Genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2020, help_text='Используйте формат: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Год издания'),
        ),
    ]
