# Generated by Django 3.0.6 on 2020-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0009_auto_20200710_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='author.Author'),
        ),
    ]
