# Generated by Django 3.0.6 on 2020-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200712_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Формат'),
        ),
    ]
