# Generated by Django 3.0.6 on 2020-07-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('book', '0015_auto_20200712_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='publisher.Publisher'),
            preserve_default=False,
        ),
    ]
