# Generated by Django 3.0.6 on 2020-07-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('book', '0016_auto_20200712_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='series.Series', verbose_name='Серия'),
        ),
    ]
